export type Quality = "4K" | "HD" | "SD";

export type Channel = {
  name: string;
  category: string;
  quality: Quality;
};

export const categories = [
  "All",
  "UK Entertainment",
  "Sports",
  "Movies & Cinema",
  "News",
  "Kids",
  "Music",
  "International",
  "Documentary",
  "Adult",
] as const;

export type Category = (typeof categories)[number];

export const channels: Channel[] = [
  // UK Entertainment
  { name: "BBC One", category: "UK Entertainment", quality: "4K" },
  { name: "BBC Two", category: "UK Entertainment", quality: "HD" },
  { name: "BBC Three", category: "UK Entertainment", quality: "HD" },
  { name: "BBC Four", category: "UK Entertainment", quality: "HD" },
  { name: "ITV", category: "UK Entertainment", quality: "4K" },
  { name: "ITV2", category: "UK Entertainment", quality: "HD" },
  { name: "ITV3", category: "UK Entertainment", quality: "HD" },
  { name: "ITV4", category: "UK Entertainment", quality: "HD" },
  { name: "ITVX", category: "UK Entertainment", quality: "HD" },
  { name: "Channel 4", category: "UK Entertainment", quality: "4K" },
  { name: "E4", category: "UK Entertainment", quality: "HD" },
  { name: "More4", category: "UK Entertainment", quality: "HD" },
  { name: "4Seven", category: "UK Entertainment", quality: "HD" },
  { name: "Channel 5", category: "UK Entertainment", quality: "4K" },
  { name: "5Star", category: "UK Entertainment", quality: "HD" },
  { name: "5USA", category: "UK Entertainment", quality: "HD" },
  { name: "Dave", category: "UK Entertainment", quality: "HD" },
  { name: "W", category: "UK Entertainment", quality: "HD" },
  { name: "Really", category: "UK Entertainment", quality: "HD" },
  { name: "Drama", category: "UK Entertainment", quality: "HD" },
  { name: "Gold", category: "UK Entertainment", quality: "HD" },
  { name: "Yesterday", category: "UK Entertainment", quality: "HD" },
  { name: "Sky One", category: "UK Entertainment", quality: "4K" },
  { name: "Sky Two", category: "UK Entertainment", quality: "HD" },
  { name: "Sky Atlantic", category: "UK Entertainment", quality: "4K" },
  { name: "Sky Max", category: "UK Entertainment", quality: "HD" },
  { name: "Sky Showcase", category: "UK Entertainment", quality: "HD" },
  { name: "Comedy Central", category: "UK Entertainment", quality: "HD" },
  { name: "E! Entertainment", category: "UK Entertainment", quality: "HD" },
  { name: "TLC", category: "UK Entertainment", quality: "HD" },
  { name: "Bravo", category: "UK Entertainment", quality: "HD" },
  { name: "Living", category: "UK Entertainment", quality: "HD" },

  // Sports
  { name: "Sky Sports Main Event", category: "Sports", quality: "4K" },
  { name: "Sky Sports Premier League", category: "Sports", quality: "4K" },
  { name: "Sky Sports Football", category: "Sports", quality: "4K" },
  { name: "Sky Sports Cricket", category: "Sports", quality: "HD" },
  { name: "Sky Sports Golf", category: "Sports", quality: "HD" },
  { name: "Sky Sports F1", category: "Sports", quality: "4K" },
  { name: "Sky Sports Action", category: "Sports", quality: "HD" },
  { name: "Sky Sports Arena", category: "Sports", quality: "HD" },
  { name: "Sky Sports Mix", category: "Sports", quality: "HD" },
  { name: "Sky Sports News", category: "Sports", quality: "HD" },
  { name: "TNT Sports 1", category: "Sports", quality: "4K" },
  { name: "TNT Sports 2", category: "Sports", quality: "HD" },
  { name: "TNT Sports 3", category: "Sports", quality: "HD" },
  { name: "TNT Sports 4", category: "Sports", quality: "HD" },
  { name: "TNT Sports Ultimate", category: "Sports", quality: "4K" },
  { name: "BT Sport 1", category: "Sports", quality: "HD" },
  { name: "BT Sport 2", category: "Sports", quality: "HD" },
  { name: "BT Sport 3", category: "Sports", quality: "HD" },
  { name: "Eurosport 1", category: "Sports", quality: "HD" },
  { name: "Eurosport 2", category: "Sports", quality: "HD" },
  { name: "ESPN", category: "Sports", quality: "HD" },
  { name: "ESPN 2", category: "Sports", quality: "HD" },
  { name: "beIN Sports 1", category: "Sports", quality: "HD" },
  { name: "beIN Sports 2", category: "Sports", quality: "HD" },
  { name: "DAZN 1", category: "Sports", quality: "4K" },
  { name: "DAZN 2", category: "Sports", quality: "HD" },
  { name: "Premier Sports 1", category: "Sports", quality: "HD" },
  { name: "Premier Sports 2", category: "Sports", quality: "HD" },
  { name: "Racing TV", category: "Sports", quality: "HD" },
  { name: "At The Races", category: "Sports", quality: "HD" },

  // Movies & Cinema
  { name: "Sky Cinema Premiere", category: "Movies & Cinema", quality: "4K" },
  { name: "Sky Cinema Action", category: "Movies & Cinema", quality: "4K" },
  { name: "Sky Cinema Comedy", category: "Movies & Cinema", quality: "HD" },
  { name: "Sky Cinema Drama", category: "Movies & Cinema", quality: "HD" },
  { name: "Sky Cinema Family", category: "Movies & Cinema", quality: "HD" },
  { name: "Sky Cinema Thriller", category: "Movies & Cinema", quality: "HD" },
  { name: "Sky Cinema Sci-Fi & Horror", category: "Movies & Cinema", quality: "HD" },
  { name: "Sky Cinema Select", category: "Movies & Cinema", quality: "4K" },
  { name: "Sky Cinema Greats", category: "Movies & Cinema", quality: "HD" },
  { name: "Film4", category: "Movies & Cinema", quality: "HD" },
  { name: "Film4+1", category: "Movies & Cinema", quality: "HD" },
  { name: "TCM", category: "Movies & Cinema", quality: "HD" },
  { name: "Sony Movies", category: "Movies & Cinema", quality: "HD" },
  { name: "Sony Movies Classic", category: "Movies & Cinema", quality: "HD" },
  { name: "Sony Movies Action", category: "Movies & Cinema", quality: "HD" },
  { name: "Legend", category: "Movies & Cinema", quality: "HD" },
  { name: "Legend Xtra", category: "Movies & Cinema", quality: "HD" },
  { name: "HBO", category: "Movies & Cinema", quality: "4K" },
  { name: "HBO 2", category: "Movies & Cinema", quality: "HD" },
  { name: "Cinemax", category: "Movies & Cinema", quality: "HD" },
  { name: "Showtime", category: "Movies & Cinema", quality: "HD" },

  // News
  { name: "BBC News", category: "News", quality: "HD" },
  { name: "Sky News", category: "News", quality: "HD" },
  { name: "GB News", category: "News", quality: "HD" },
  { name: "TalkTV", category: "News", quality: "HD" },
  { name: "CNN International", category: "News", quality: "HD" },
  { name: "CNN USA", category: "News", quality: "HD" },
  { name: "Fox News", category: "News", quality: "HD" },
  { name: "MSNBC", category: "News", quality: "HD" },
  { name: "Al Jazeera English", category: "News", quality: "HD" },
  { name: "Al Jazeera Arabic", category: "News", quality: "HD" },
  { name: "BBC World News", category: "News", quality: "HD" },
  { name: "Bloomberg", category: "News", quality: "HD" },
  { name: "CNBC", category: "News", quality: "HD" },
  { name: "Euronews", category: "News", quality: "HD" },
  { name: "France 24", category: "News", quality: "HD" },
  { name: "DW News", category: "News", quality: "HD" },
  { name: "RT News", category: "News", quality: "HD" },

  // Kids
  { name: "CBeebies", category: "Kids", quality: "HD" },
  { name: "CBBC", category: "Kids", quality: "HD" },
  { name: "Nickelodeon", category: "Kids", quality: "HD" },
  { name: "Nick Jr", category: "Kids", quality: "HD" },
  { name: "NickToons", category: "Kids", quality: "HD" },
  { name: "Cartoon Network", category: "Kids", quality: "HD" },
  { name: "Boomerang", category: "Kids", quality: "HD" },
  { name: "Disney Channel", category: "Kids", quality: "HD" },
  { name: "Disney Junior", category: "Kids", quality: "HD" },
  { name: "Disney XD", category: "Kids", quality: "HD" },
  { name: "Sky Kids", category: "Kids", quality: "HD" },
  { name: "Baby TV", category: "Kids", quality: "HD" },
  { name: "Tiny Pop", category: "Kids", quality: "HD" },
  { name: "Pop", category: "Kids", quality: "HD" },
  { name: "Pop Max", category: "Kids", quality: "HD" },
  { name: "Ketchup TV", category: "Kids", quality: "HD" },

  // Music
  { name: "MTV", category: "Music", quality: "HD" },
  { name: "MTV Base", category: "Music", quality: "HD" },
  { name: "MTV Hits", category: "Music", quality: "HD" },
  { name: "MTV Classic", category: "Music", quality: "HD" },
  { name: "VH1", category: "Music", quality: "HD" },
  { name: "Kerrang!", category: "Music", quality: "HD" },
  { name: "Magic TV", category: "Music", quality: "HD" },
  { name: "Absolute Radio", category: "Music", quality: "HD" },
  { name: "Kiss TV", category: "Music", quality: "HD" },
  { name: "4Music", category: "Music", quality: "HD" },
  { name: "The Box", category: "Music", quality: "HD" },
  { name: "Box Hits", category: "Music", quality: "HD" },
  { name: "Box Upfront", category: "Music", quality: "HD" },
  { name: "Clubland TV", category: "Music", quality: "HD" },

  // Documentary
  { name: "National Geographic", category: "Documentary", quality: "HD" },
  { name: "National Geographic Wild", category: "Documentary", quality: "HD" },
  { name: "Discovery Channel", category: "Documentary", quality: "HD" },
  { name: "Discovery Science", category: "Documentary", quality: "HD" },
  { name: "Discovery History", category: "Documentary", quality: "HD" },
  { name: "Discovery Turbo", category: "Documentary", quality: "HD" },
  { name: "Animal Planet", category: "Documentary", quality: "HD" },
  { name: "History Channel", category: "Documentary", quality: "HD" },
  { name: "History 2", category: "Documentary", quality: "HD" },
  { name: "Crime + Investigation", category: "Documentary", quality: "HD" },
  { name: "Investigation Discovery", category: "Documentary", quality: "HD" },
  { name: "Eden", category: "Documentary", quality: "HD" },
  { name: "Nat Geo People", category: "Documentary", quality: "HD" },
  { name: "Travel Channel", category: "Documentary", quality: "HD" },
  { name: "Quest", category: "Documentary", quality: "HD" },
  { name: "Quest Red", category: "Documentary", quality: "HD" },

  // International
  { name: "MBC 1", category: "International", quality: "HD" },
  { name: "MBC Drama", category: "International", quality: "HD" },
  { name: "MBC Action", category: "International", quality: "HD" },
  { name: "MBC Masr", category: "International", quality: "HD" },
  { name: "Dubai TV", category: "International", quality: "HD" },
  { name: "Abu Dhabi TV", category: "International", quality: "HD" },
  { name: "Rotana Cinema", category: "International", quality: "HD" },
  { name: "Rotana Khalijia", category: "International", quality: "HD" },
  { name: "TF1", category: "International", quality: "HD" },
  { name: "France 2", category: "International", quality: "HD" },
  { name: "France 3", category: "International", quality: "HD" },
  { name: "M6", category: "International", quality: "HD" },
  { name: "Canal+", category: "International", quality: "HD" },
  { name: "ARD", category: "International", quality: "HD" },
  { name: "ZDF", category: "International", quality: "HD" },
  { name: "RTL", category: "International", quality: "HD" },
  { name: "Rai Uno", category: "International", quality: "HD" },
  { name: "Rai Due", category: "International", quality: "HD" },
  { name: "Rai Tre", category: "International", quality: "HD" },
  { name: "Canale 5", category: "International", quality: "HD" },
  { name: "TVE 1", category: "International", quality: "HD" },
  { name: "Antena 3", category: "International", quality: "HD" },
  { name: "Star Plus", category: "International", quality: "HD" },
  { name: "Zee TV", category: "International", quality: "HD" },
  { name: "Sony TV", category: "International", quality: "HD" },
  { name: "Colors TV", category: "International", quality: "HD" },
  { name: "Star Gold", category: "International", quality: "HD" },
  { name: "TV5 Monde", category: "International", quality: "HD" },
  { name: "NHK World", category: "International", quality: "HD" },
  { name: "CGTN", category: "International", quality: "HD" },
];
